version: '3.8'

services:
  server:
    image: node:18
    container_name: server
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run start:dev"
    env_file:
      - ./.env
    depends_on:
      - pg-db
    ports:
      - '${PORT}:${PORT}'

  pg-db:
    image: postgres:15
    container_name: pg-db
    env_file:
      - ./.env.db
    ports:
      - '5432:5432'
